### PR TITLE
draft readme

### PR DESCRIPTION
**Pull request by andrewMacmurray**

### CODE REVIEW

**Comment by sofer** [comment]
I love this.

**Comment by iteles** [comment]
Was this ready to be merged seeing as it hadn't been assigned to anyone? @andrewMacmurray Are you guys planning on following any processes for this project too?

**Comment by andrewMacmurray** [comment]
@iteles it wasn't strictly ready to be merged yet but it's ok as it was just the initial draft of the readme. And yes don't worry we'll follow standard processes 😉  (it is my day off btw so go lightly! 😆 )

**Comment by iteles** [comment]
hahaha Well, I don't want to ruin the fun!

I'm coming at it more from the angle of: if this is something we're going to use extensively in F&C there will be a lot of eyes on this repo, so practicing what we preach is probably a good thing :blush:

If it's at all helpful, I'm super happy to spend some time with you both nailing down the process side of things. I'll be creating the tl;dr for https://github.com/dwyl/contributing soon, but it'll probably be very similar to this: https://github.com/dwyl/contributing/issues/28 (I was having a rough day when I wrote it 😆 )

Tell me what you need from me in general for this, I consider it my pet project since we discussed it at the funding meeting and *really* want to help make it work (only if I add value and am not a hinderance).

**Comment by andrewMacmurray** [comment]
@iteles no that's great, it's super helpful having a watchful eye over the project.

If you have time at some point to go through the process side of things that would be great, when are you back from web summit?

**Comment by iteles** [comment]
I'm back! I'll be dropping by the office tomorrow morning or I'll be in on Monday. 😊

**Comment by andrewMacmurray** [comment]
great! we're both in tomorrow 😄

**Comment by ivanmauricio** [comment]
This issue was moved to keep-the-lights-on/keep-the-lights-on#9

**Pull request merged**
